package me.pascal.nekobot.command

import net.dv8tion.jda.api.entities.Message

class CommandHandler {

    val commands = arrayListOf<Command>(
        Command("femdom", LEVEL.NSFW, TYPE.IMAGE),
        Command("tickle", LEVEL.SFW, TYPE.IMAGE),
        Command("classic", LEVEL.NSFW, TYPE.IMAGE),
        Command("ngif", LEVEL.NSFW, TYPE.IMAGE),
        Command("erofeet", LEVEL.NSFW, TYPE.IMAGE),
        Command("meow", LEVEL.SFW, TYPE.IMAGE),
        Command("erok", LEVEL.NSFW, TYPE.IMAGE),
        Command("poke", LEVEL.SFW, TYPE.IMAGE),
        Command("les", LEVEL.NSFW, TYPE.IMAGE),
        Command("hololewd", LEVEL.NSFW, TYPE.IMAGE),
        Command("lewdk", LEVEL.NSFW, TYPE.IMAGE),
        Command("keta", LEVEL.NSFW, TYPE.IMAGE),
        Command("feetg", LEVEL.NSFW, TYPE.IMAGE),
        Command("nsfw_neko_gif", LEVEL.NSFW, TYPE.IMAGE),
        Command("eroyuri", LEVEL.NSFW, TYPE.IMAGE),
        Command("kiss", LEVEL.SFW, TYPE.IMAGE),
        Command("8ball", LEVEL.SFW, TYPE.IMAGE),
        Command("kuni", LEVEL.NSFW, TYPE.IMAGE),
        Command("tits", LEVEL.NSFW, TYPE.IMAGE),
        Command("pussy_jpg", LEVEL.NSFW, TYPE.IMAGE),
        Command("cum_jpg", LEVEL.NSFW, TYPE.IMAGE),
        Command("pussy", LEVEL.NSFW, TYPE.IMAGE),
        Command("lewdkemo", LEVEL.NSFW, TYPE.IMAGE),
        Command("lizard", LEVEL.SFW, TYPE.IMAGE),
        Command("slap", LEVEL.SFW, TYPE.IMAGE),
        Command("lewd", LEVEL.NSFW, TYPE.IMAGE),
        Command("cum", LEVEL.NSFW, TYPE.IMAGE),
        Command("cuddle", LEVEL.SFW, TYPE.IMAGE),
        Command("spank", LEVEL.NSFW, TYPE.IMAGE),
        Command("goose", LEVEL.SFW, TYPE.IMAGE),
        Command("Random_hentai_gif", LEVEL.NSFW, TYPE.IMAGE),
        Command("avatar", LEVEL.SFW, TYPE.IMAGE),
        Command("fox_girl", LEVEL.SFW, TYPE.IMAGE),
        Command("nsfw_avatar", LEVEL.NSFW, TYPE.IMAGE),
        Command("hug", LEVEL.SFW, TYPE.IMAGE),
        Command("gecg", LEVEL.SFW, TYPE.IMAGE),
        Command("boobs", LEVEL.NSFW, TYPE.IMAGE),
        Command("pat", LEVEL.SFW, TYPE.IMAGE),
        Command("feet", LEVEL.NSFW, TYPE.IMAGE),
        Command("smug", LEVEL.SFW, TYPE.IMAGE),
        Command("kemonomimi", LEVEL.SFW, TYPE.IMAGE),
        Command("solog", LEVEL.NSFW, TYPE.IMAGE),
        Command("holo", LEVEL.SFW, TYPE.IMAGE),
        Command("wallpaper", LEVEL.NSFW, TYPE.IMAGE),
        Command("bj", LEVEL.NSFW, TYPE.IMAGE),
        Command("woof", LEVEL.SFW, TYPE.IMAGE),
        Command("yuri", LEVEL.NSFW, TYPE.IMAGE),
        Command("trap", LEVEL.NSFW, TYPE.IMAGE),
        Command("anal", LEVEL.NSFW, TYPE.IMAGE),
        Command("baka", LEVEL.SFW, TYPE.IMAGE),
        Command("blowjob", LEVEL.NSFW, TYPE.IMAGE),
        Command("holoero", LEVEL.NSFW, TYPE.IMAGE),
        Command("feed", LEVEL.SFW, TYPE.IMAGE),
        Command("neko", LEVEL.SFW, TYPE.IMAGE),
        Command("gasm", LEVEL.SFW, TYPE.IMAGE),
        Command("hentai", LEVEL.NSFW, TYPE.IMAGE),
        Command("futanari", LEVEL.NSFW, TYPE.IMAGE),
        Command("ero", LEVEL.NSFW, TYPE.IMAGE),
        Command("solo", LEVEL.NSFW, TYPE.IMAGE),
        Command("waifu", LEVEL.SFW, TYPE.IMAGE),
        Command("pwankg", LEVEL.NSFW, TYPE.IMAGE),
        Command("eron", LEVEL.NSFW, TYPE.IMAGE),
        Command("erokemo", LEVEL.NSFW, TYPE.IMAGE)
    )

    fun handle(message: Message) {

    }
}